import 'product_model.dart';

const List<Product> products = [
  Product(
    id: 'nike-noir-runner',
    name: 'Nike Noir Runner',
    brand: 'Nike',
    image: 'assets/products/black_luxe_runner.jpg',
    isAssetImage: true,
    price: 86,
    category: 'Shoes',
    condition: 'Excellent',
    seller: 'Alex Morgan',
    sellerHandle: '@alexwears',
    vibe: 'Luxury sport',
    tags: ['nike', 'running', 'black', 'sneakers', 'luxury', 'athletic'],
    sizes: ['8', '9', '10', '11'],
    description:
        'Seller describes a clean black performance runner with icy accents, built for everyday wear.',
  ),
  Product(
    id: 'nike-red-court',
    name: 'Nike Red Court',
    brand: 'Nike',
    image: 'assets/products/red_court_sneaker.jpg',
    isAssetImage: true,
    price: 92,
    category: 'Shoes',
    condition: 'Good',
    seller: 'Jordan Lee',
    sellerHandle: '@jordanscloset',
    vibe: 'Basketball',
    tags: ['nike', 'basketball', 'red', 'court', 'sneakers', 'sport'],
    sizes: ['7', '8', '9', '10', '12'],
    description:
        'Bold red court sneakers with a premium shape and strong hoop-day energy.',
  ),
  Product(
    id: 'white-heavy-tee',
    name: 'White Heavy Tee',
    brand: 'Drip Studio',
    image: 'assets/products/white_luxe_tee.jpg',
    isAssetImage: true,
    price: 38,
    category: 'T-Shirts',
    condition: 'New',
    seller: 'Mia Carter',
    sellerHandle: '@miacloset',
    vibe: 'Minimal luxury',
    tags: ['tee', 't-shirt', 'white', 'blank', 'minimal', 'luxury'],
    sizes: ['S', 'M', 'L', 'XL'],
    description:
        'Heavyweight blank tee with a relaxed luxury fit. Easy to style with denim, cargos, or shorts.',
  ),
  Product(
    id: 'black-heavy-tee',
    name: 'Midnight Heavy Tee',
    brand: 'Drip Studio',
    image: 'assets/products/black_luxe_tee.jpg',
    isAssetImage: true,
    price: 42,
    category: 'T-Shirts',
    condition: 'Excellent',
    seller: 'Noah King',
    sellerHandle: '@noahfits',
    vibe: 'Night out',
    tags: ['tee', 't-shirt', 'black', 'minimal', 'luxury', 'streetwear'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description:
        'A crisp black oversized tee with premium texture and a clean silhouette.',
  ),
  Product(
    id: 'adidas-green-terrace',
    name: 'Adidas Green Terrace',
    brand: 'Adidas',
    image: 'assets/products/adidas_green_terrace.jpg',
    isAssetImage: true,
    price: 74,
    category: 'Shoes',
    condition: 'Excellent',
    seller: 'Sam Rivera',
    sellerHandle: '@samvault',
    vibe: 'Terrace classic',
    tags: ['adidas', 'terrace', 'green', 'gum sole', 'sneakers', 'vintage'],
    sizes: ['7', '8', '9', '10', '11'],
    description:
        'A clean green terrace sneaker with a gum sole and vintage sport energy.',
  ),
  Product(
    id: 'puma-black-suede',
    name: 'Puma Black Suede',
    brand: 'Puma',
    image: 'assets/products/puma_black_suede.jpg',
    isAssetImage: true,
    price: 68,
    category: 'Shoes',
    condition: 'Good',
    seller: 'Chris Taylor',
    sellerHandle: '@chrishoops',
    vibe: 'Suede low',
    tags: ['puma', 'suede', 'black', 'gum sole', 'sneakers', 'streetwear'],
    sizes: ['7', '8', '9', '10', '11'],
    description:
        'A black suede low-top with a gum sole and a small red hit on the heel.',
  ),
  Product(
    id: 'cloud-practice-tee',
    name: 'Sage Heavy Tee',
    brand: 'Stone Island',
    image: 'assets/products/sage_heavy_tee.jpg',
    isAssetImage: true,
    price: 34,
    category: 'T-Shirts',
    condition: 'Excellent',
    seller: 'Jay Brooks',
    sellerHandle: '@jayfinds',
    vibe: 'Muted streetwear',
    tags: ['streetwear', 'tee', 'sage', 'green', 'luxury', 't-shirt'],
    sizes: ['S', 'M', 'L', 'XL'],
    description:
        'A sage heavyweight tee with a relaxed shape and premium muted color.',
  ),
  Product(
    id: 'black-gallery-tee',
    name: 'Washed Purple Graphic Tee',
    brand: 'Palace',
    image: 'assets/products/washed_purple_graphic_tee.jpg',
    isAssetImage: true,
    price: 46,
    category: 'T-Shirts',
    condition: 'Good',
    seller: 'Ava Stone',
    sellerHandle: '@avastyle',
    vibe: 'Washed graphic',
    tags: ['purple', 'tee', 't-shirt', 'graphic', 'streetwear', 'palace'],
    sizes: ['M', 'L', 'XL'],
    description:
        'A washed purple oversized tee with abstract graphic energy and a vintage handfeel.',
  ),
  Product(
    id: 'balenciaga-neon-chunky',
    name: 'Balenciaga Neon Chunky',
    brand: 'Balenciaga',
    image: 'assets/products/balenciaga_neon_chunky.jpg',
    isAssetImage: true,
    price: 99,
    category: 'Shoes',
    condition: 'Excellent',
    seller: 'Lena Park',
    sellerHandle: '@lenalooks',
    vibe: 'Luxury chunky',
    tags: ['balenciaga', 'designer', 'chunky', 'luxury', 'sneakers', 'neon'],
    sizes: ['6', '7', '8', '9', '10'],
    description:
        'A chunky designer runner with silver layers and neon detail for loud luxury fits.',
  ),
  Product(
    id: 'cream-luxe-tee',
    name: 'Cream Crop Tee',
    brand: 'Fear of God',
    image: 'assets/products/cream_crop_tee.jpg',
    isAssetImage: true,
    price: 32,
    category: 'T-Shirts',
    condition: 'New',
    seller: 'Eli Moore',
    sellerHandle: '@elimarket',
    vibe: 'Soft luxury',
    tags: ['tee', 'cream', 'white', 'luxury', 'minimal', 'fear of god'],
    sizes: ['S', 'M', 'L', 'XL'],
    description:
        'A cream cropped heavyweight tee for clean layered fits and warm-weather basics.',
  ),
  Product(
    id: 'rick-owens-black-boot',
    name: 'Rick Owens Black Boot',
    brand: 'Rick Owens',
    image: 'assets/products/rick_owens_black_boot.jpg',
    isAssetImage: true,
    price: 98,
    category: 'Shoes',
    condition: 'Good',
    seller: 'Ava Stone',
    sellerHandle: '@avastyle',
    vibe: 'Avant-garde',
    tags: ['rick owens', 'designer', 'black', 'boot', 'high top', 'luxury'],
    sizes: ['8', '9', '10', '11'],
    description:
        'A black high-top sneaker boot with dramatic proportions and dark runway energy.',
  ),
  Product(
    id: 'vans-black-canvas',
    name: 'Vans Black Canvas',
    brand: 'Vans',
    image: 'assets/products/vans_black_canvas.jpg',
    isAssetImage: true,
    price: 44,
    category: 'Shoes',
    condition: 'Excellent',
    seller: 'Jay Brooks',
    sellerHandle: '@jayfinds',
    vibe: 'Skate classic',
    tags: ['vans', 'skate', 'canvas', 'black', 'low top', 'streetwear'],
    sizes: ['7', '8', '9', '10', '11', '12'],
    description:
        'A clean black canvas skate shoe that works with cargos, denim, and graphic tees.',
  ),
  Product(
    id: 'asics-blue-silver-runner',
    name: 'ASICS Blue Silver Runner',
    brand: 'ASICS',
    image: 'assets/products/blue_silver_runner.jpg',
    isAssetImage: true,
    price: 82,
    category: 'Shoes',
    condition: 'Excellent',
    seller: 'Sam Rivera',
    sellerHandle: '@samvault',
    vibe: 'Tech runner',
    tags: ['asics', 'running', 'blue', 'silver', 'mesh', 'sneakers'],
    sizes: ['7', '8', '9', '10', '11'],
    description:
        'A blue and silver tech runner with mesh panels and a futuristic sport look.',
  ),
  Product(
    id: 'jordan-cream-orange-court',
    name: 'Jordan Cream Orange Court',
    brand: 'Jordan',
    image: 'assets/products/cream_orange_court.jpg',
    isAssetImage: true,
    price: 88,
    category: 'Shoes',
    condition: 'Good',
    seller: 'Jordan Lee',
    sellerHandle: '@jordanscloset',
    vibe: 'Court luxury',
    tags: ['jordan', 'basketball', 'cream', 'orange', 'court', 'sneakers'],
    sizes: ['7', '8', '9', '10', '11', '12'],
    description:
        'A cream and orange court sneaker with bold panels and premium hoop-day energy.',
  ),
  Product(
    id: 'basic-white-tee',
    name: 'Basic White Tee',
    brand: 'Drip Basics',
    price: 18,
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600',
    category: 'Shirts',
    condition: 'New',
    seller: 'Mia Carter',
    sellerHandle: '@miacloset',
    vibe: 'Clean essential',
    tags: ['shirts', 'shirt', 'tee', 'white', 'basic', 'minimal', 'luxury'],
    sizes: ['S', 'M', 'L', 'XL'],
    description:
        'A crisp white everyday tee for clean fits, layering, and low-key luxury looks.',
  ),
  Product(
    id: 'black-oversized-tee',
    name: 'Black Oversized Tee',
    brand: 'Drip Basics',
    price: 22,
    image: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=600',
    category: 'Shirts',
    condition: 'Excellent',
    seller: 'Noah King',
    sellerHandle: '@noahfits',
    vibe: 'Oversized street',
    tags: ['shirts', 'shirt', 'tee', 'black', 'oversized', 'streetwear'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description:
        'A black oversized tee with an easy streetwear shape and soft worn-in feel.',
  ),
  Product(
    id: 'vintage-graphic-shirt',
    name: 'Vintage Graphic Shirt',
    brand: 'Archive Room',
    price: 25,
    image: 'https://images.unsplash.com/photo-1523381294911-8d3cead13475?w=600',
    category: 'Shirts',
    condition: 'Good',
    seller: 'Ava Stone',
    sellerHandle: '@avastyle',
    vibe: 'Vintage graphic',
    tags: ['shirts', 'shirt', 'graphic', 'vintage', 'tee', 'archive'],
    sizes: ['S', 'M', 'L'],
    description:
        'A vintage-style graphic shirt that adds character without pushing the price up.',
  ),
  Product(
    id: 'streetwear-tee',
    name: 'Metal Table Graphic Tee',
    brand: 'Supreme',
    price: 48,
    image: 'assets/products/metal_graphic_tee.jpg',
    isAssetImage: true,
    category: 'Shirts',
    condition: 'Excellent',
    seller: 'Jay Brooks',
    sellerHandle: '@jayfinds',
    vibe: 'Flash graphic',
    tags: ['shirts', 'shirt', 'tee', 'streetwear', 'graphic', 'supreme'],
    sizes: ['S', 'M', 'L', 'XL'],
    description:
        'A washed graphic tee staged on a metal table with flash-photo streetwear energy.',
  ),
  Product(
    id: 'clean-beige-tee',
    name: 'Clean Beige Tee',
    brand: 'Drip Basics',
    price: 19,
    image: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=600',
    category: 'Shirts',
    condition: 'New',
    seller: 'Eli Moore',
    sellerHandle: '@elimarket',
    vibe: 'Soft neutral',
    tags: ['shirts', 'shirt', 'tee', 'beige', 'cream', 'neutral', 'luxury'],
    sizes: ['S', 'M', 'L', 'XL'],
    description:
        'A clean beige tee for soft neutral outfits and simple luxury layering.',
  ),
  Product(
    id: 'black-puffer-jacket',
    name: 'Black Puffer Jacket',
    brand: 'Winter Vault',
    price: 55,
    image: 'https://images.unsplash.com/photo-1543076447-215ad9ba6923?w=600',
    category: 'Jackets',
    condition: 'Excellent',
    seller: 'Riley Knox',
    sellerHandle: '@rileyvault',
    vibe: 'Cold weather flex',
    tags: ['jacket', 'jackets', 'black', 'puffer', 'winter', 'streetwear'],
    sizes: ['S', 'M', 'L', 'XL'],
    description:
        'A warm black puffer jacket that brings volume and streetwear polish to winter fits.',
  ),
  Product(
    id: 'denim-jacket',
    name: 'Denim Jacket',
    brand: 'Blue Archive',
    price: 45,
    image: 'https://images.unsplash.com/photo-1516257984-b1b4d707412e?w=600',
    category: 'Jackets',
    condition: 'Good',
    seller: 'Sam Rivera',
    sellerHandle: '@samvault',
    vibe: 'Classic denim',
    tags: ['jacket', 'jackets', 'denim', 'blue', 'classic', 'vintage'],
    sizes: ['S', 'M', 'L', 'XL'],
    description:
        'A classic denim jacket for easy layering over tees, hoodies, and neutral basics.',
  ),
  Product(
    id: 'brown-work-jacket',
    name: 'Brown Work Jacket',
    brand: 'Utility Supply',
    price: 50,
    image: 'https://images.unsplash.com/photo-1520975954732-35dd22299614?w=600',
    category: 'Jackets',
    condition: 'Excellent',
    seller: 'Chris Taylor',
    sellerHandle: '@chrishoops',
    vibe: 'Workwear',
    tags: ['jacket', 'jackets', 'brown', 'workwear', 'utility', 'streetwear'],
    sizes: ['M', 'L', 'XL'],
    description:
        'A brown work jacket with utility energy and a clean resale-friendly price.',
  ),
  Product(
    id: 'street-bomber-jacket',
    name: 'Leather Sleeve Varsity',
    brand: 'Represent',
    price: 72,
    image: 'assets/products/chair_varsity_jacket_natural_v2.jpg',
    isAssetImage: true,
    category: 'Jackets',
    condition: 'Good',
    seller: 'Jordan Lee',
    sellerHandle: '@jordanscloset',
    vibe: 'Sunlit varsity',
    tags: ['jacket', 'jackets', 'varsity', 'streetwear', 'black', 'cream'],
    sizes: ['S', 'M', 'L'],
    description:
        'A black and cream varsity jacket photographed in soft window light so the materials and condition read clearly.',
  ),
  Product(
    id: 'grey-zip-jacket',
    name: 'Grey Zip Jacket',
    brand: 'Drip Basics',
    price: 38,
    image: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=600',
    category: 'Jackets',
    condition: 'Good',
    seller: 'Lena Park',
    sellerHandle: '@lenalooks',
    vibe: 'Clean layer',
    tags: ['jacket', 'jackets', 'grey', 'zip', 'minimal', 'layer'],
    sizes: ['S', 'M', 'L', 'XL'],
    description:
        'A grey zip jacket for simple layering, travel days, and everyday outfits.',
  ),
  Product(
    id: 'red-sneakers',
    name: 'Red Sneakers',
    brand: 'Court Supply',
    price: 65,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600',
    category: 'Shoes',
    condition: 'Excellent',
    seller: 'Jordan Lee',
    sellerHandle: '@jordanscloset',
    vibe: 'Bold sneakers',
    tags: ['shoes', 'sneakers', 'red', 'streetwear', 'sport', 'basketball'],
    sizes: ['7', '8', '9', '10', '11'],
    description:
        'Bright red sneakers for users who want their shoes to be the loudest part of the fit.',
  ),
  Product(
    id: 'white-running-shoes',
    name: 'White Running Shoes',
    brand: 'Run Club',
    price: 58,
    image: 'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=600',
    category: 'Shoes',
    condition: 'Good',
    seller: 'Lena Park',
    sellerHandle: '@lenalooks',
    vibe: 'Running clean',
    tags: ['shoes', 'sneakers', 'white', 'running', 'gym', 'athletic'],
    sizes: ['6', '7', '8', '9', '10'],
    description:
        'White running shoes for gym-to-street styling and clean daily movement.',
  ),
  Product(
    id: 'black-street-sneakers',
    name: 'Black Street Sneakers',
    brand: 'Street Supply',
    price: 70,
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600',
    category: 'Shoes',
    condition: 'Excellent',
    seller: 'Alex Morgan',
    sellerHandle: '@alexwears',
    vibe: 'Black street',
    tags: ['shoes', 'sneakers', 'black', 'streetwear', 'daily', 'luxury'],
    sizes: ['8', '9', '10', '11', '12'],
    description:
        'Black street sneakers that work with almost any outfit in the marketplace.',
  ),
  Product(
    id: 'classic-low-sneakers',
    name: 'Classic Low Sneakers',
    brand: 'Archive Room',
    price: 60,
    image: 'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=600',
    category: 'Shoes',
    condition: 'Good',
    seller: 'Ava Stone',
    sellerHandle: '@avastyle',
    vibe: 'Classic low',
    tags: ['shoes', 'sneakers', 'classic', 'low', 'white', 'minimal'],
    sizes: ['7', '8', '9', '10', '11'],
    description:
        'A classic low sneaker shape for simple outfits and reliable everyday wear.',
  ),
  Product(
    id: 'blue-sneakers',
    name: 'Blue Sneakers',
    brand: 'Run Club',
    price: 62,
    image: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600',
    category: 'Shoes',
    condition: 'Excellent',
    seller: 'Sam Rivera',
    sellerHandle: '@samvault',
    vibe: 'Blue runner',
    tags: ['shoes', 'sneakers', 'blue', 'running', 'athletic', 'daily'],
    sizes: ['7', '8', '9', '10'],
    description:
        'Blue sneakers with a sporty look for running errands, workouts, and casual fits.',
  ),
  Product(
    id: 'chunky-white-sneakers',
    name: 'Chunky White Sneakers',
    brand: 'Street Supply',
    price: 75,
    image: 'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=600',
    category: 'Shoes',
    condition: 'Good',
    seller: 'Noah King',
    sellerHandle: '@noahfits',
    vibe: 'Chunky luxury',
    tags: ['shoes', 'sneakers', 'chunky', 'white', 'luxury', 'streetwear'],
    sizes: ['8', '9', '10', '11'],
    description:
        'Chunky white sneakers that make simple outfits feel heavier and more styled.',
  ),
  Product(
    id: 'grey-hoodie',
    name: 'Rack Charcoal Hoodie',
    brand: 'Essentials',
    price: 54,
    image: 'assets/products/rack_charcoal_hoodie.jpg',
    isAssetImage: true,
    category: 'Hoodies',
    condition: 'Excellent',
    seller: 'Jay Brooks',
    sellerHandle: '@jayfinds',
    vibe: 'Neon rack shot',
    tags: ['hoodie', 'hoodies', 'charcoal', 'rack', 'streetwear', 'essentials'],
    sizes: ['S', 'M', 'L', 'XL'],
    description:
        'A charcoal oversized hoodie shot on a rack with concrete and blue neon behind it.',
  ),
  Product(
    id: 'black-hoodie',
    name: 'Black Hoodie',
    brand: 'Drip Basics',
    price: 40,
    image: 'https://images.unsplash.com/photo-1578768079052-aa76e52ff62e?w=600',
    category: 'Hoodies',
    condition: 'Good',
    seller: 'Noah King',
    sellerHandle: '@noahfits',
    vibe: 'Black staple',
    tags: ['hoodie', 'hoodies', 'black', 'basic', 'streetwear', 'daily'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description:
        'A black hoodie staple for users who want one layer that goes with everything.',
  ),
  Product(
    id: 'cream-hoodie',
    name: 'Cream Hoodie',
    brand: 'Drip Basics',
    price: 38,
    image: 'https://images.unsplash.com/photo-1578587018452-892bacefd3f2?w=600',
    category: 'Hoodies',
    condition: 'Excellent',
    seller: 'Eli Moore',
    sellerHandle: '@elimarket',
    vibe: 'Soft neutral',
    tags: ['hoodie', 'hoodies', 'cream', 'neutral', 'minimal', 'luxury'],
    sizes: ['S', 'M', 'L', 'XL'],
    description:
        'A cream hoodie for soft neutral looks and warm layered outfits.',
  ),
  Product(
    id: 'oversized-hoodie',
    name: 'Oversized Hoodie',
    brand: 'Street Supply',
    price: 42,
    image: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=600',
    category: 'Hoodies',
    condition: 'Good',
    seller: 'Riley Knox',
    sellerHandle: '@rileyvault',
    vibe: 'Oversized comfort',
    tags: ['hoodie', 'hoodies', 'oversized', 'streetwear', 'cozy', 'layer'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    description:
        'An oversized hoodie for relaxed silhouettes, cozy fits, and colder evenings.',
  ),
  Product(
    id: 'black-cargo-pants',
    name: 'Concrete Olive Cargos',
    brand: 'Carhartt WIP',
    price: 58,
    image: 'assets/products/concrete_olive_cargos.jpg',
    isAssetImage: true,
    category: 'Pants',
    condition: 'Good',
    seller: 'Chris Taylor',
    sellerHandle: '@chrishoops',
    vibe: 'Concrete flat-lay',
    tags: ['pants', 'cargo', 'olive', 'utility', 'streetwear', 'carhartt'],
    sizes: ['S', 'M', 'L', 'XL'],
    description:
        'Olive cargo pants flat-laid on concrete with a belt and dark styling around it.',
  ),
  Product(
    id: 'blue-denim-jeans',
    name: 'Blue Denim Jeans',
    brand: 'Blue Archive',
    price: 32,
    image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=600',
    category: 'Pants',
    condition: 'Good',
    seller: 'Sam Rivera',
    sellerHandle: '@samvault',
    vibe: 'Classic denim',
    tags: ['pants', 'jeans', 'denim', 'blue', 'classic', 'vintage'],
    sizes: ['28', '30', '32', '34', '36'],
    description:
        'Blue denim jeans for classic fits, sneaker outfits, and everyday resale basics.',
  ),
  Product(
    id: 'relaxed-fit-jeans',
    name: 'Relaxed Fit Jeans',
    brand: 'Blue Archive',
    price: 36,
    image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600',
    category: 'Pants',
    condition: 'Excellent',
    seller: 'Ava Stone',
    sellerHandle: '@avastyle',
    vibe: 'Relaxed denim',
    tags: ['pants', 'jeans', 'denim', 'relaxed', 'blue', 'daily'],
    sizes: ['28', '30', '32', '34'],
    description:
        'Relaxed fit jeans that give outfits more shape without feeling too wide.',
  ),
  Product(
    id: 'tan-cargo-pants',
    name: 'Tan Cargo Pants',
    brand: 'Utility Supply',
    price: 34,
    image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600',
    category: 'Pants',
    condition: 'Excellent',
    seller: 'Lena Park',
    sellerHandle: '@lenalooks',
    vibe: 'Neutral utility',
    tags: ['pants', 'cargo', 'tan', 'utility', 'neutral', 'streetwear'],
    sizes: ['S', 'M', 'L', 'XL'],
    description:
        'Tan cargo pants for neutral outfits with utility pockets and a clean street feel.',
  ),
  Product(
    id: 'rack-baggy-denim',
    name: 'Rack Baggy Denim',
    brand: 'Stüssy',
    price: 62,
    image: 'assets/products/rack_baggy_denim_natural_v2.jpg',
    isAssetImage: true,
    category: 'Pants',
    condition: 'Excellent',
    seller: 'Sam Rivera',
    sellerHandle: '@samvault',
    vibe: 'Natural-light denim',
    tags: ['pants', 'jeans', 'denim', 'baggy', 'streetwear', 'stussy'],
    sizes: ['28', '30', '32', '34', '36'],
    description:
        'Baggy blue denim photographed in natural window light with the full relaxed shape visible.',
  ),
  Product(
    id: 'concrete-layered-fit',
    name: 'Concrete Layered Fit',
    brand: 'Drip Curated',
    price: 76,
    image: 'assets/products/concrete_layered_fit.jpg',
    isAssetImage: true,
    category: 'Outfits',
    condition: 'New',
    seller: 'Mia Carter',
    sellerHandle: '@miacloset',
    vibe: 'Styled bundle',
    tags: ['outfit', 'bundle', 'streetwear', 'vest', 'tee', 'shorts'],
    sizes: ['S', 'M', 'L', 'XL'],
    description:
        'A full flat-lay streetwear bundle with a work vest, heavyweight tee, shorts, chain, and cap.',
  ),
  Product(
    id: 'black-cap',
    name: 'Black Cap',
    brand: 'Drip Accessories',
    price: 15,
    image: 'https://images.unsplash.com/photo-1521369909029-2afed882baee?w=600',
    category: 'Accessories',
    condition: 'New',
    seller: 'Mia Carter',
    sellerHandle: '@miacloset',
    vibe: 'Simple accessory',
    tags: ['accessories', 'cap', 'hat', 'black', 'minimal', 'streetwear'],
    sizes: ['One size'],
    description:
        'A black cap for finishing outfits without overthinking the accessory.',
  ),
  Product(
    id: 'streetwear-beanie',
    name: 'Shelf Burgundy Beanie',
    brand: 'Stüssy',
    price: 24,
    image: 'assets/products/shelf_burgundy_beanie.jpg',
    isAssetImage: true,
    category: 'Accessories',
    condition: 'Excellent',
    seller: 'Riley Knox',
    sellerHandle: '@rileyvault',
    vibe: 'Shelf accessory',
    tags: ['accessories', 'beanie', 'hat', 'streetwear', 'winter', 'stussy'],
    sizes: ['One size'],
    description:
        'A burgundy ribbed beanie staged on an industrial boutique shelf with blue light.',
  ),
  Product(
    id: 'crossbody-bag',
    name: 'Shelf Crossbody Bag',
    brand: 'A-COLD-WALL*',
    price: 36,
    image: 'assets/products/shelf_crossbody_bag.jpg',
    isAssetImage: true,
    category: 'Accessories',
    condition: 'Good',
    seller: 'Jay Brooks',
    sellerHandle: '@jayfinds',
    vibe: 'Shelf product shot',
    tags: ['accessories', 'bag', 'crossbody', 'utility', 'streetwear', 'black'],
    sizes: ['One size'],
    description:
        'A black crossbody sling bag staged on an industrial shelf with blue neon light.',
  ),
  Product(
    id: 'black-backpack',
    name: 'Black Backpack',
    brand: 'Utility Supply',
    price: 30,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600',
    category: 'Accessories',
    condition: 'Good',
    seller: 'Alex Morgan',
    sellerHandle: '@alexwears',
    vibe: 'Everyday carry',
    tags: ['accessories', 'backpack', 'bag', 'black', 'utility', 'daily'],
    sizes: ['One size'],
    description:
        'A black backpack for daily carry, school, travel, and clean practical outfits.',
  ),
];

const List<SellerStory> sellerStories = [
  SellerStory(
    seller: 'Alex',
    handle: '@alexwears',
    title: 'Sneaker wall under \$100',
    accent: 'Mixed brands',
    productIds: [
      'black-street-sneakers',
      'black-backpack',
      'adidas-green-terrace',
    ],
  ),
  SellerStory(
    seller: 'Jordan',
    handle: '@jordanscloset',
    title: 'Court and skate drops',
    accent: 'Fresh soles',
    productIds: ['red-sneakers', 'street-bomber-jacket', 'nike-red-court'],
  ),
  SellerStory(
    seller: 'Mia',
    handle: '@miacloset',
    title: 'Luxury tees',
    accent: 'Clean basics',
    productIds: ['basic-white-tee', 'black-cap', 'concrete-layered-fit'],
  ),
  SellerStory(
    seller: 'Ava',
    handle: '@avastyle',
    title: 'Designer darkness',
    accent: 'Runway vibe',
    productIds: [
      'clean-beige-tee',
      'relaxed-fit-jeans',
      'classic-low-sneakers',
    ],
  ),
  SellerStory(
    seller: 'Riley',
    handle: '@rileyvault',
    title: 'Jackets and hoodies',
    accent: 'Layer season',
    productIds: [
      'black-puffer-jacket',
      'oversized-hoodie',
      'streetwear-beanie',
    ],
  ),
  SellerStory(
    seller: 'Sam',
    handle: '@samvault',
    title: 'Denim and runners',
    accent: 'Everyday picks',
    productIds: ['denim-jacket', 'blue-denim-jeans', 'rack-baggy-denim'],
  ),
  SellerStory(
    seller: 'Jay',
    handle: '@jayfinds',
    title: 'Accessories under \$30',
    accent: 'Finish the fit',
    productIds: ['streetwear-tee', 'crossbody-bag', 'grey-hoodie'],
  ),
];

final List<ShopperRank> topShoppers = List.generate(100, (index) {
  final names = [
    'Malik',
    'Zoe',
    'Andre',
    'Nia',
    'Kai',
    'Imani',
    'Leo',
    'Sofia',
    'Miles',
    'Amara',
  ];
  final name = names[index % names.length];
  final rank = index + 1;
  return ShopperRank(
    rank: rank,
    name: '$name ${rank == 1 ? 'Crown' : 'Vault'}',
    handle: '@${name.toLowerCase()}shops$rank',
    spent: 980 - (rank * 7.25),
    orders: 42 - (rank ~/ 4),
  );
});
